-- Add prescription metadata fields
DO $$
BEGIN
  CREATE TYPE "UsageMode" AS ENUM ('FIXED', 'AS_NEEDED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "Prescription" ADD COLUMN IF NOT EXISTS "validUntil" TIMESTAMP(3);
ALTER TABLE "Prescription" ADD COLUMN IF NOT EXISTS "dosageText" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Prescription" ADD COLUMN IF NOT EXISTS "pharmacistName" TEXT NOT NULL DEFAULT '';

-- Ensure reminder columns exist (guards against schema drift)
ALTER TABLE "CustomerReminder" ADD COLUMN IF NOT EXISTS "lastOrderedAt" TIMESTAMP(3);
ALTER TABLE "CustomerReminder" ADD COLUMN IF NOT EXISTS "note" TEXT NOT NULL DEFAULT '';
ALTER TABLE "CustomerReminder" ADD COLUMN IF NOT EXISTS "isPaused" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "CustomerReminder" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Add order item snapshot + refill tracking fields
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "purchaseDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "packQuantitySnapshot" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "unitTypeSnapshot" TEXT NOT NULL DEFAULT '';
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "recommendedDosageAmountSnapshot" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "recommendedDosageUnitSnapshot" TEXT NOT NULL DEFAULT '';
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "recommendedFrequencyPerDaySnapshot" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "recommendedUsageTextSnapshot" TEXT NOT NULL DEFAULT '';
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "usageModeSnapshot" "UsageMode" NOT NULL DEFAULT 'FIXED';
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "refillableSnapshot" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "reorderableSnapshot" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "manualOverrideEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "manualDosageAmount" DOUBLE PRECISION;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "manualFrequencyPerDay" DOUBLE PRECISION;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "manualDaysSupply" INTEGER;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "manualUsageText" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "isPaused" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "pausedAt" TIMESTAMP(3);
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "pausedDays" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "dosageRecommendedByName" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "dosageRecommendedByRole" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "dosageRecommendedAt" TIMESTAMP(3);
