ALTER TABLE "public"."ShippingAddress"
  ADD COLUMN IF NOT EXISTS "formattedAddress" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "addressProvider" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "providerPlaceId" TEXT NOT NULL DEFAULT '';
