ALTER TABLE "CustomerReminder" ADD COLUMN IF NOT EXISTS "lastOrderedAt" TIMESTAMP(3);
ALTER TABLE "CustomerReminder" ADD COLUMN IF NOT EXISTS "note" TEXT NOT NULL DEFAULT '';
ALTER TABLE "CustomerReminder" ADD COLUMN IF NOT EXISTS "isPaused" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "CustomerReminder" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
