ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryProvider" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryOrderNo" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryStatus" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryTrackingUrl" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryMeta" JSONB;
